### PR TITLE
modernize cSeedMapGenerator a bit and include it only where used

### PR DESCRIPTION
**Pull request by pbomta**
Some cleanup. Returning the seedmap from the generator by value, as NRVO (named return value optimization) will construct it in-place and no copy will be done. In case that fails, the seedmap contains only one vector, which supports move semantics, so the data buffer is not copied if the original object is not used anymore.

### CODE REVIEW

**Comment by stefanhendriks** [comment]
I'd need to test this a bit in campaign mode but it looks ok to me :)

**Comment by stefanhendriks** [comment]
I'll test this now

**Comment by stefanhendriks** [comment]
I start an `Atreides` campaign , and I immediately get a crash (SIGSEV):

image

Not sure why though.

**Comment by stefanhendriks** [comment]
I unfolded `map` in debug view:

image

Could it be that it tries to insert at index `14` within the vector while there is only `0` and `1` and you need to have them in order? (can't be having gaps I suppose, as it is more like an array right?)

**Comment by stefanhendriks** [comment]
When retrying I get a SIGSEV on a totally different place. 

I'm not sure what happened, this would require some backtracking and figuring out when it went wrong (git is our friend).

**Review by stefanhendriks — CHANGES_REQUESTED** [review]
Please investigate why it crashes :)

**Comment by stefanhendriks** [comment]
FYI, I tested on `master` and that works

**Comment by pbomta** [comment]
> Please investigate why it crashes :)

Ah, I just saw this. Thanks for testing! I'll take a look.
When I tested it, it worked. Good that we're more than one person.

**Comment by pbomta** [comment]
> Could it be that it tries to insert at index `14` within the vector while there is only `0` and `1`

Oh, no! Of course. I ran into a tricky corner of C++ that several blogposts warn you for! 
See here: https://hackingcpp.com/cpp/std/vector.html expand "Make New Vectors". There the case is explained.

**Comment by pbomta** [comment]
I tested it only in skirmish mode, but now I see that doesn't even use the seedmap.

**Comment by stefanhendriks** [comment]
> 

true. Skirmish mode has a different map generator.

**Comment by stefanhendriks** [comment]
> > Could it be that it tries to insert at index `14` within the vector while there is only `0` and `1`
> 
> Oh, no! Of course. I ran into a tricky corner of C++ that several blogposts warn you for! See here: https://hackingcpp.com/cpp/std/vector.html expand "Make New Vectors". There the case is explained.

haha, nice. It is a subtle difference but has great impact ;-)

**Pull request merged**
