### PR TITLE
Rewriting/fmt control

### PR DESCRIPTION
**Pull request by Akatsuki57**
Just transfer my deported branch to a local branch

### CODE REVIEW

**Comment by Akatsuki57** [comment]
If i merge this branch, the new code will be into [stefanhendriks:rewriting/fmt_control](https://github.com/stefanhendriks/Dune-II---The-Maker/tree/rewriting/fmt_control)  not in main ?

**Comment by stefanhendriks** [comment]
You need to change the `base` where you want to merge this into.

Plz wait for merge before @pbomta or I have seen it. (and the build should be green for both Windows & Linux ofc :) )

**Comment by stefanhendriks** [comment]
You can change base by clicking "Edit" (at the right). Then you can change base to `master`:

image

**Comment by Akatsuki57** [comment]
Misunderstanding !
I would like to create a new branch with the one I had already built on the fork of your directory.
Also, the branch is currently a working branch not ready to be integrated into production.

**Pull request closed without merging**
