### PR TITLE
Build: introduce CMake import targets for direct dependencies

### PR DESCRIPTION
**Pull request by pbomta**
Hi Stefan, what a cool project! I loved Dune 2 a lot when I was a kid.

You asked for a different approach to link the dependencies in the CMakeLists.txt file 
We can use "import targets" for that. They turn an include directory and a binary artifact into a CMake target that can be added as a dependency to the main executable.

I organized the dependencies too so that each has an "include" directory and a "lib" directory.

### CODE REVIEW

**Comment by stefanhendriks** [comment]
This relates to (I think) https://github.com/stefanhendriks/Dune-II---The-Maker/issues/58, possibly affects https://github.com/stefanhendriks/Dune-II---The-Maker/issues/200 

If there is any other issue you mean @pbomta , please let me know, so I can tie this in.

**Comment by stefanhendriks** [comment]
I pulled your PR and updated the `readme.md`. I do wonder if you had to do anything specific with header files to have d2tm compile for you?

**Comment by stefanhendriks** [comment]
I tested on my environment, with updated `cmake`, also removing all my allegro / dependency related files which I had in my `minGW` dir and it compiles flawlessly. It also compiles under command-line (I usually test under CLion, but I really would like to have it IDE-independent obviously). 

Looks like it works fine.

**Comment by stefanhendriks** [comment]
Testing a bit, I see this now (something with alfont). I've seen this before, I'll check the dependencies a bit to see how they are different from my local machine (when i switch back to `master` it works fine):

image

**Comment by stefanhendriks** [comment]
I found a different .lib file to link against, with that the weird artifacts we're gone.

**Comment by pbomta** [comment]
> This relates to (I think) #58, possibly affects #200
> 
> If there is any other issue you mean @pbomta , please let me know, so I can tie this in.
Ah, but I didn't compile on Linux. I have MSYS2 installed on my Windows laptop and then used mingw32 to make use of the binaries that got checked in source control. Good to read that you want to move away from that, by the way.

I went through all the open issues and didn't find any that refers to this fix.

**Comment by pbomta** [comment]
> I do wonder if you had to do anything specific with header files to have d2tm compile for you?

Nope, That was what I wanted to achieve. ;) I didn't want to copy any allegro stuff into my mingw installation. So I could just pull the project from github, run cmake and ninja (I prefer ninja over make) to build it.

**Pull request merged**
